test_that("contribution tables add up", {
  m <- example_uk_dairy_2022()
  eco <- uk_dairy_2022_economics()
  res <- deconflate(m, method = "published")
  ct <- contribution_table(res, eco)
  expect_equal(nrow(ct), 3 * 13)
  vl <- value_losses(productivity_gap(res, eco$observed), eco$unit_value)
  expect_equal(sum(ct$value), sum(vl$by_outcome$value), tolerance = 1e-10)
  expect_equal(unname(c(tapply(ct$share, ct$outcome, sum))), c(1, 1, 1))
  s <- summary(res, economics = eco)
  expect_output(print(s), "Comorbidity adjustment")
  expect_equal(attr(s$totals, "total_value"), 402.24755302935023, tolerance = 1e-9)
})

test_that("plots draw without error", {
  grDevices::pdf(NULL)
  on.exit(grDevices::dev.off())
  res <- deconflate(example_uk_dairy_2022(), method = "published")
  expect_invisible(plot(res, outcome = "yield"))
  expect_invisible(plot_burden(res))
  expect_invisible(plot_burden(res, uk_dairy_2022_economics()))
  expect_invisible(plot(screen_associations(example_supplement())))
  expect_invisible(plot(sensitivity_oat(example_supplement())))
  s <- cm_sampler(example_supplement(), impacts = list("yield:d1" = dist_normal(2.5, 0.5)))
  expect_invisible(plot(cm_monte_carlo(s, 20, seed = 1)))
})
